import type { Product } from '../types/product';

// Fuente de verdad inicial: estos 12 productos también se cargan en la migración SQL
// 0002_products_seed.sql para que el sitio arranque con datos en producción.
// En dev, si el cliente de Supabase no devuelve productos (no hay env vars o falla la red),
// useProducts cae a este array como fallback offline.

export const SEED_PRODUCTS: Product[] = [
  {
    id: 1, slug: 'fin-grass-plus', name: 'FIN-GRASS PLUS', category: 'Desengrasante',
    headline: 'El desengrasante que las flotas de colectivo eligen desde hace 20 años',
    description: 'Formulado para eliminar grasa carbonizada en motores, pisos de talleres y cocinas industriales. Alta concentración: rinde hasta 1:20 en dilución. Biodegradable.',
    story: 'Desarrollado originalmente para los talleres de mantenimiento de una de las flotas de colectivos más grandes de Buenos Aires. Hoy es nuestro producto más vendido.',
    industries: ['Transporte', 'Gastronomía', 'Industria'],
    benefits: ['Alto rendimiento', 'Biodegradable', 'Alta concentración'],
    presentations: ['Bidón 5L', 'Bidón 20L', 'Tambor 200L'],
    tags: [],
    dilution: '1:10 a 1:20 según aplicación', ph: '12-13 (alcalino)',
    image_url: 'https://femavi.com.ar/wp-content/uploads/2024/04/30-litros-25-300x300.png',
    featured: true, display_order: 1, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 2, slug: 'bactericida-industrial', name: 'BACTERICIDA INDUSTRIAL', category: 'Desinfectante',
    headline: 'Desinfección de amplio espectro para superficies en contacto con alimentos',
    description: 'Bactericida de cuarta generación con acción residual prolongada. Elimina bacterias, hongos y levaduras en superficies industriales. Apto para industria alimenticia.',
    story: 'Nació de una necesidad concreta: una cadena gastronómica necesitaba un solo producto que desinfectara cocinas, cámaras frigoríficas y áreas de servicio sin cambiar de fórmula.',
    industries: ['Gastronomía', 'Edificios', 'Salud'],
    benefits: ['Apto alimenticio', 'Acción residual', 'Amplio espectro'],
    presentations: ['Bidón 5L', 'Bidón 20L', 'Tambor 200L'],
    tags: [],
    dilution: '1:50 a 1:100', ph: '6.5-7.5 (neutro)',
    image_url: 'https://femavi.com.ar/wp-content/uploads/2024/03/barril-10-300x300.png',
    featured: true, display_order: 2, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 3, slug: 'cera-acrilica-premium', name: 'CERA ACRÍLICA PREMIUM', category: 'Cera',
    headline: 'Brillo profesional que dura semanas, no días',
    description: 'Cera autobrillante de altísima resistencia al tránsito. Forma una película protectora transparente que resiste marcas de zapatos, agua y productos de limpieza diaria.',
    story: 'Los facility managers de edificios corporativos en Microcentro la piden por nombre. Un solo lustrado rinde hasta 3 semanas en pisos de alto tránsito.',
    industries: ['Edificios', 'Comercios', 'Salud'],
    benefits: ['Larga duración', 'Autobrillante', 'Resistente al tránsito'],
    presentations: ['Bidón 5L', 'Bidón 20L'],
    tags: [],
    dilution: 'Aplicar sin diluir', ph: '8-9',
    image_url: 'https://femavi.com.ar/wp-content/uploads/2024/04/Untitled-design-2-300x300.png',
    featured: true, display_order: 3, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 4, slug: 'flox', name: 'FLOX', category: 'Aromatizante',
    headline: 'El aromatizante industrial que se convirtió en clásico',
    description: 'Aromatizante concentrado en aerosol para ambientes de gran volumen. Neutraliza olores en lugar de enmascararlos. Fragancia profesional de larga duración.',
    story: 'Tiene fans. Literalmente. Es el producto que más nos piden por nombre propio. Hay clientes que lo usan hace más de 15 años y nunca cambiaron.',
    industries: ['Edificios', 'Transporte', 'Comercios'],
    benefits: ['Neutraliza olores', 'Larga duración', 'Concentrado'],
    presentations: ['Aerosol 440cc', 'Aerosol 220cc'],
    tags: [],
    dilution: 'N/A — listo para usar', ph: 'N/A',
    image_url: 'https://femavi.com.ar/wp-content/uploads/2024/03/AEREOSOLES-6-300x300.png',
    featured: true, display_order: 4, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 5, slug: 'fexolite', name: 'FEXOLITE', category: 'Limpiador',
    headline: 'Un solo bidón para todo el piso de producción',
    description: 'Limpiador multiuso de ultra concentración para pisos, paredes y superficies industriales. Desplaza grasas livianas, suciedad acumulada y manchas de uso diario.',
    story: 'Lo diseñamos pensando en empresas que necesitan simplificar su inventario de limpieza. Un producto, múltiples superficies, rendimiento que justifica cada peso.',
    industries: ['Industria', 'Edificios', 'Transporte'],
    benefits: ['Ultra concentrado', 'Multiuso', 'Económico por rendimiento'],
    presentations: ['Bidón 5L', 'Bidón 20L', 'Tambor 200L'],
    tags: [],
    dilution: '1:20 a 1:40', ph: '7-8 (neutro)',
    image_url: 'https://femavi.com.ar/wp-content/uploads/2024/04/20-litros-23-300x300.png',
    featured: true, display_order: 5, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 6, slug: 'aceite-alimenticio-sae-10', name: 'ACEITE ALIMENTICIO SAE 10', category: 'Aceite',
    headline: 'Lubricación segura donde la comida pasa primero',
    description: 'Aceite mineral de grado alimenticio para maquinaria en contacto incidental con alimentos. Inodoro, insípido, cumple normativas de seguridad alimentaria.',
    story: 'Usado en panificadoras, frigoríficos y plantas de envasado de alimentos. Cuando la maquinaria está cerca de la línea de producción, este es el aceite que corresponde.',
    industries: ['Gastronomía', 'Industria'],
    benefits: ['Grado alimenticio', 'Inodoro', 'Cumple normativas'],
    presentations: ['Bidón 20L', 'Tambor 200L'],
    tags: [],
    dilution: 'N/A — uso directo', ph: 'N/A',
    image_url: 'https://femavi.com.ar/wp-content/uploads/2024/04/30-litros-1-1-300x300.png',
    featured: false, display_order: 6, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 7, slug: 'abrinox', name: 'ABRINOX', category: 'Anticorrosivo',
    headline: 'Protección anticorrosiva para piezas que no pueden fallar',
    description: 'Recubrimiento anticorrosivo de película seca para piezas metálicas, herramientas y componentes de precisión. Protección de larga duración sin residuo graso.',
    story: 'Lo usan talleres metalúrgicos que necesitan almacenar piezas mecanizadas durante semanas sin riesgo de oxidación. Protege sin manchar.',
    industries: ['Industria', 'Automotor'],
    benefits: ['Alto rendimiento', 'Larga duración', 'Seguridad industrial'],
    presentations: ['Aerosol 440cc', 'Bidón 5L', 'Bidón 20L'],
    tags: [],
    dilution: 'N/A', ph: 'N/A',
    image_url: 'https://femavi.com.ar/wp-content/uploads/2024/04/Copy-of-Untitled-Design-300x300.png',
    featured: false, display_order: 7, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 8, slug: 'absorb', name: 'ABSORB', category: 'Absorbente',
    headline: 'Derrame controlado en segundos, no en horas',
    description: 'Tierra absorbente industrial de alta capacidad para derrames de aceites, combustibles y químicos. Absorbe hasta 4 veces su peso.',
    story: 'En plantas industriales y estaciones de servicio, un derrame mal manejado es un riesgo de seguridad y una multa ambiental. Absorb resuelve el problema en el acto.',
    industries: ['Industria', 'Automotor', 'Transporte'],
    benefits: ['Alto rendimiento', 'Seguridad industrial', 'Multiuso'],
    presentations: ['Bolsa 25kg', 'Pallet'],
    tags: [],
    dilution: 'N/A — uso directo', ph: 'N/A (inerte)',
    image_url: 'https://femavi.com.ar/wp-content/uploads/2024/04/ABSORB-3-300x300.png',
    featured: false, display_order: 8, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 9, slug: 'lavamanos-industrial', name: 'LAVAMANOS INDUSTRIAL', category: 'Higiene',
    headline: 'Manos limpias sin agua corriente en el taller',
    description: 'Pasta lavamanos con micropartículas abrasivas que elimina grasa, pintura, resina y adhesivos sin dañar la piel.',
    story: 'En talleres mecánicos y plantas de producción donde el jabón común no alcanza. Limpia lo que otros productos no pueden.',
    industries: ['Industria', 'Automotor', 'Transporte'],
    benefits: ['Multiuso', 'Biodegradable', 'Alto rendimiento'],
    presentations: ['Pote 500g', 'Pote 3.5kg', 'Balde 10kg'],
    tags: [],
    dilution: 'N/A', ph: '5.5-6 (pH piel)',
    image_url: 'https://femavi.com.ar/wp-content/uploads/2024/04/Copy-of-Untitled-Design-300x300.png',
    featured: false, display_order: 9, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 10, slug: 'detergente-concentrado', name: 'DETERGENTE CONCENTRADO', category: 'Detergente',
    headline: 'Rendimiento real: un bidón rinde como cinco',
    description: 'Detergente industrial de ultra concentración para baldeo de pisos. Baja espuma, ideal para máquinas lavadoras de piso.',
    story: 'Las empresas de limpieza que lo adoptan reducen su costo por metro cuadrado limpio a menos de la mitad.',
    industries: ['Edificios', 'Comercios', 'Empresas de limpieza'],
    benefits: ['Ultra concentrado', 'Económico por rendimiento', 'Multiuso'],
    presentations: ['Bidón 5L', 'Bidón 20L', 'Tambor 200L'],
    tags: [],
    dilution: '1:40 a 1:80', ph: '7-8',
    image_url: 'https://femavi.com.ar/wp-content/uploads/2024/03/barril-10-300x300.png',
    featured: false, display_order: 10, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 11, slug: 'solvente-dielectrico', name: 'SOLVENTE DIELÉCTRICO', category: 'Solvente',
    headline: 'Limpieza segura de componentes eléctricos energizados',
    description: 'Solvente de rápida evaporación para limpieza de tableros eléctricos, motores y componentes electrónicos. No conduce electricidad.',
    story: 'Mantenimiento eléctrico industrial sin cortar la energía. Lo usan técnicos de planta que necesitan limpiar sin parar la producción.',
    industries: ['Industria', 'Transporte'],
    benefits: ['Seguridad industrial', 'Alto rendimiento', 'Larga duración'],
    presentations: ['Aerosol 440cc', 'Bidón 5L'],
    tags: [],
    dilution: 'N/A — uso directo', ph: 'N/A',
    image_url: 'https://femavi.com.ar/wp-content/uploads/2024/04/Copy-of-Untitled-Design-300x300.png',
    featured: false, display_order: 11, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 12, slug: 'tratamiento-para-aguas', name: 'TRATAMIENTO PARA AGUAS', category: 'Tratamiento',
    headline: 'Agua tratada sin tercerizaciones costosas',
    description: 'Floculantes, antiincrustantes y biocidas para torres de enfriamiento, calderas y circuitos cerrados.',
    story: 'Plantas que gastaban fortunas en servicios tercerizados hoy lo resuelven internamente con nuestra línea y soporte técnico incluido.',
    industries: ['Industria', 'Gastronomía'],
    benefits: ['Económico por rendimiento', 'Ultra concentrado', 'Multiuso'],
    presentations: ['Bidón 20L', 'Tambor 200L'],
    tags: [],
    dilution: 'Según análisis de agua', ph: 'Variable',
    image_url: 'https://femavi.com.ar/wp-content/uploads/2024/03/barril-10-300x300.png',
    featured: false, display_order: 12, is_active: true,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
];
