-- Carga inicial de los 12 productos del catálogo histórico de FEMAVI.
-- Ya aplicado en el proyecto FEMAVI (mvtqjsgpahddjdbiuazg).

insert into public.products (slug, name, category, headline, description, story, industries, benefits, presentations, dilution, ph, image_url, featured, display_order) values
('fin-grass-plus', 'FIN-GRASS PLUS', 'Desengrasante',
 'El desengrasante que las flotas de colectivo eligen desde hace 20 años',
 'Formulado para eliminar grasa carbonizada en motores, pisos de talleres y cocinas industriales. Alta concentración: rinde hasta 1:20 en dilución. Biodegradable.',
 'Desarrollado originalmente para los talleres de mantenimiento de una de las flotas de colectivos más grandes de Buenos Aires. Hoy es nuestro producto más vendido.',
 array['Transporte','Gastronomía','Industria'],
 array['Alto rendimiento','Biodegradable','Alta concentración'],
 array['Bidón 5L','Bidón 20L','Tambor 200L'],
 '1:10 a 1:20 según aplicación', '12-13 (alcalino)',
 'https://femavi.com.ar/wp-content/uploads/2024/04/30-litros-25-300x300.png', true, 1),
('bactericida-industrial', 'BACTERICIDA INDUSTRIAL', 'Desinfectante',
 'Desinfección de amplio espectro para superficies en contacto con alimentos',
 'Bactericida de cuarta generación con acción residual prolongada. Elimina bacterias, hongos y levaduras en superficies industriales. Apto para industria alimenticia.',
 'Nació de una necesidad concreta: una cadena gastronómica necesitaba un solo producto que desinfectara cocinas, cámaras frigoríficas y áreas de servicio sin cambiar de fórmula.',
 array['Gastronomía','Edificios','Salud'],
 array['Apto alimenticio','Acción residual','Amplio espectro'],
 array['Bidón 5L','Bidón 20L','Tambor 200L'],
 '1:50 a 1:100', '6.5-7.5 (neutro)',
 'https://femavi.com.ar/wp-content/uploads/2024/03/barril-10-300x300.png', true, 2),
('cera-acrilica-premium', 'CERA ACRÍLICA PREMIUM', 'Cera',
 'Brillo profesional que dura semanas, no días',
 'Cera autobrillante de altísima resistencia al tránsito. Forma una película protectora transparente que resiste marcas de zapatos, agua y productos de limpieza diaria.',
 'Los facility managers de edificios corporativos en Microcentro la piden por nombre. Un solo lustrado rinde hasta 3 semanas en pisos de alto tránsito.',
 array['Edificios','Comercios','Salud'],
 array['Larga duración','Autobrillante','Resistente al tránsito'],
 array['Bidón 5L','Bidón 20L'],
 'Aplicar sin diluir', '8-9',
 'https://femavi.com.ar/wp-content/uploads/2024/04/Untitled-design-2-300x300.png', true, 3),
('flox', 'FLOX', 'Aromatizante',
 'El aromatizante industrial que se convirtió en clásico',
 'Aromatizante concentrado en aerosol para ambientes de gran volumen. Neutraliza olores en lugar de enmascararlos. Fragancia profesional de larga duración.',
 'Tiene fans. Literalmente. Es el producto que más nos piden por nombre propio. Hay clientes que lo usan hace más de 15 años y nunca cambiaron.',
 array['Edificios','Transporte','Comercios'],
 array['Neutraliza olores','Larga duración','Concentrado'],
 array['Aerosol 440cc','Aerosol 220cc'],
 'N/A — listo para usar', 'N/A',
 'https://femavi.com.ar/wp-content/uploads/2024/03/AEREOSOLES-6-300x300.png', true, 4),
('fexolite', 'FEXOLITE', 'Limpiador',
 'Un solo bidón para todo el piso de producción',
 'Limpiador multiuso de ultra concentración para pisos, paredes y superficies industriales. Desplaza grasas livianas, suciedad acumulada y manchas de uso diario.',
 'Lo diseñamos pensando en empresas que necesitan simplificar su inventario de limpieza. Un producto, múltiples superficies, rendimiento que justifica cada peso.',
 array['Industria','Edificios','Transporte'],
 array['Ultra concentrado','Multiuso','Económico por rendimiento'],
 array['Bidón 5L','Bidón 20L','Tambor 200L'],
 '1:20 a 1:40', '7-8 (neutro)',
 'https://femavi.com.ar/wp-content/uploads/2024/04/20-litros-23-300x300.png', true, 5),
('aceite-alimenticio-sae-10', 'ACEITE ALIMENTICIO SAE 10', 'Aceite',
 'Lubricación segura donde la comida pasa primero',
 'Aceite mineral de grado alimenticio para maquinaria en contacto incidental con alimentos. Inodoro, insípido, cumple normativas de seguridad alimentaria.',
 'Usado en panificadoras, frigoríficos y plantas de envasado de alimentos. Cuando la maquinaria está cerca de la línea de producción, este es el aceite que corresponde.',
 array['Gastronomía','Industria'],
 array['Grado alimenticio','Inodoro','Cumple normativas'],
 array['Bidón 20L','Tambor 200L'],
 'N/A — uso directo', 'N/A',
 'https://femavi.com.ar/wp-content/uploads/2024/04/30-litros-1-1-300x300.png', false, 6),
('abrinox', 'ABRINOX', 'Anticorrosivo',
 'Protección anticorrosiva para piezas que no pueden fallar',
 'Recubrimiento anticorrosivo de película seca para piezas metálicas, herramientas y componentes de precisión. Protección de larga duración sin residuo graso.',
 'Lo usan talleres metalúrgicos que necesitan almacenar piezas mecanizadas durante semanas sin riesgo de oxidación. Protege sin manchar.',
 array['Industria','Automotor'],
 array['Alto rendimiento','Larga duración','Seguridad industrial'],
 array['Aerosol 440cc','Bidón 5L','Bidón 20L'],
 'N/A', 'N/A',
 'https://femavi.com.ar/wp-content/uploads/2024/04/Copy-of-Untitled-Design-300x300.png', false, 7),
('absorb', 'ABSORB', 'Absorbente',
 'Derrame controlado en segundos, no en horas',
 'Tierra absorbente industrial de alta capacidad para derrames de aceites, combustibles y químicos. Absorbe hasta 4 veces su peso.',
 'En plantas industriales y estaciones de servicio, un derrame mal manejado es un riesgo de seguridad y una multa ambiental. Absorb resuelve el problema en el acto.',
 array['Industria','Automotor','Transporte'],
 array['Alto rendimiento','Seguridad industrial','Multiuso'],
 array['Bolsa 25kg','Pallet'],
 'N/A — uso directo', 'N/A (inerte)',
 'https://femavi.com.ar/wp-content/uploads/2024/04/ABSORB-3-300x300.png', false, 8),
('lavamanos-industrial', 'LAVAMANOS INDUSTRIAL', 'Higiene',
 'Manos limpias sin agua corriente en el taller',
 'Pasta lavamanos con micropartículas abrasivas que elimina grasa, pintura, resina y adhesivos sin dañar la piel.',
 'En talleres mecánicos y plantas de producción donde el jabón común no alcanza. Limpia lo que otros productos no pueden.',
 array['Industria','Automotor','Transporte'],
 array['Multiuso','Biodegradable','Alto rendimiento'],
 array['Pote 500g','Pote 3.5kg','Balde 10kg'],
 'N/A', '5.5-6 (pH piel)',
 'https://femavi.com.ar/wp-content/uploads/2024/04/Copy-of-Untitled-Design-300x300.png', false, 9),
('detergente-concentrado', 'DETERGENTE CONCENTRADO', 'Detergente',
 'Rendimiento real: un bidón rinde como cinco',
 'Detergente industrial de ultra concentración para baldeo de pisos. Baja espuma, ideal para máquinas lavadoras de piso.',
 'Las empresas de limpieza que lo adoptan reducen su costo por metro cuadrado limpio a menos de la mitad.',
 array['Edificios','Comercios','Empresas de limpieza'],
 array['Ultra concentrado','Económico por rendimiento','Multiuso'],
 array['Bidón 5L','Bidón 20L','Tambor 200L'],
 '1:40 a 1:80', '7-8',
 'https://femavi.com.ar/wp-content/uploads/2024/03/barril-10-300x300.png', false, 10),
('solvente-dielectrico', 'SOLVENTE DIELÉCTRICO', 'Solvente',
 'Limpieza segura de componentes eléctricos energizados',
 'Solvente de rápida evaporación para limpieza de tableros eléctricos, motores y componentes electrónicos. No conduce electricidad.',
 'Mantenimiento eléctrico industrial sin cortar la energía. Lo usan técnicos de planta que necesitan limpiar sin parar la producción.',
 array['Industria','Transporte'],
 array['Seguridad industrial','Alto rendimiento','Larga duración'],
 array['Aerosol 440cc','Bidón 5L'],
 'N/A — uso directo', 'N/A',
 'https://femavi.com.ar/wp-content/uploads/2024/04/Copy-of-Untitled-Design-300x300.png', false, 11),
('tratamiento-para-aguas', 'TRATAMIENTO PARA AGUAS', 'Tratamiento',
 'Agua tratada sin tercerizaciones costosas',
 'Floculantes, antiincrustantes y biocidas para torres de enfriamiento, calderas y circuitos cerrados.',
 'Plantas que gastaban fortunas en servicios tercerizados hoy lo resuelven internamente con nuestra línea y soporte técnico incluido.',
 array['Industria','Gastronomía'],
 array['Económico por rendimiento','Ultra concentrado','Multiuso'],
 array['Bidón 20L','Tambor 200L'],
 'Según análisis de agua', 'Variable',
 'https://femavi.com.ar/wp-content/uploads/2024/03/barril-10-300x300.png', false, 12);
