-- Documenta cambios que ya existen en producción (proyecto lhqawwjszwjzxxsonvwa) pero que
-- se habían aplicado manualmente desde el dashboard de Supabase sin quedar trackeados acá.
-- Este archivo es idempotente (usa IF NOT EXISTS / DROP+CREATE) para poder correrse tanto
-- en un ambiente nuevo como, sin efecto, en producción donde ya existe todo esto.

alter table public.products add column if not exists subcategory text;

create index if not exists idx_products_subcategory on public.products(subcategory) where is_active;

create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  excerpt text not null,
  content text not null,
  cover_image_url text,
  tags text[] not null default '{}',
  published boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists articles_set_updated_at on public.articles;
create trigger articles_set_updated_at before update on public.articles
  for each row execute procedure moddatetime(updated_at);

alter table public.articles enable row level security;

drop policy if exists "public can read published articles" on public.articles;
create policy "public can read published articles" on public.articles for select
  using (published = true);

drop policy if exists "authenticated can do everything" on public.articles;
create policy "authenticated can do everything" on public.articles for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');
